services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=<MONGOURI/DBNAME>
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
